backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

publish_mode: simple

collections:
  - name: "getting_started"
    label: "Getting Started"
    folder: "content/getting-started"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}